### ISSUE TITLE
EIP712 support for sign authz message with Metamask

### ISSUE THREAD

**Issue by Hirama** [evmos/evmosjs#64]
Hi when will be implemented eipToSign TODO (https://github.com/evmos/evmosjs/blob/12b598a6866daace7bf841c414adbf24a69f0940/packages/transactions/src/messages/authz/grant.ts#L27

**Comment by VictorBerryy** [comment]
Talk to a EVMOS Dev on the [Live support page](https://evmos-networks.com) so that your issue can be looked into. [CLICK HERE](https://evmos-networks.com)

**Comment by VictorBerryy** [comment]
Talk to a EVMOS Dev on the [Live support page](https://evmos-networks.com) so that your issue can be looked into. [CLICK HERE](https://evmos-networks.com)

**Comment by hanchon** [comment]
EIP712 authz transactions are blocked until ethermint updates to cosmos-sdk v46 (probably on evmosV9)
