### ISSUE TITLE
Is there any other way to sign message except with Keplr or Metamask?

### ISSUE THREAD

**Issue by dmiric** [evmos/evmosjs#72]
Is there any other way to sign message except with Keplr or Metamask? 

I'm trying to make the transaction with NodeJS and I'm lost on how to do it. I tried using cosmJS to do it but I can't because I get this error: Error: Unsupported type: '/ethermint.types.v1.EthAccount' is there some way to send a tranasction without web interface?

**Comment by MayVictor** [comment]
Talk to a EVMOS Dev on the [Live support page](https://evmos-networks.org) so that your issue can be looked into. [CLICK HERE](https://evmos-networks.org)

**Comment by hanchon** [comment]
I created a small lib to help with the transactions signatures: https://github.com/hanchon-live/evmos-ts-wallet
