### ISSUE TITLE
Support for `authz` messages apart from `StakeAuthorization` 

### ISSUE THREAD

**Issue by SusheendharVijay** [evmos/evmosjs#74]
Is there support for other `authz` messages? If yes how do I go about doing that? Since only `createTxMsgStakeAuthorization` is available in the package. For e.g if I wanted to give a `GenericAuthorization` how can I do that? Thanks!

**Comment by MayVictor** [comment]
Talk to a EVMOS Dev on the [Live support page](https://evmos-networks.org) so that your issue can be looked into. [CLICK HERE](https://evmos-networks.org)

**Comment by MayVictor** [comment]
Talk to a EVMOS Dev on the [Live support page](https://evmos-networks.org) so that your issue can be looked into. [CLICK HERE](https://evmos-networks.org)
